name: Release

on:
  push:
    branches:
      - main

# Add permissions to allow semantic-release to push to the repository
permissions:
  contents: write  # Required for pushing git tags and releases
  issues: write    # Required for creating issues
  packages: write  # Required for publishing to GitHub Packages if needed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install --no-save semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/npm @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release 